### PR TITLE
Add commands to make an epub to the Makefile

### PR DESCRIPTION
**Pull request by tijn**
I think my e-reader cannot deal with HTML and using it with PDFs is a big hassle so I created an epub version of your book. This turned out to be really easy because I could simply copy the commands from the other versions but I nevertheless wanted to share this back with you.

### CODE REVIEW

**Comment by tijn** [comment]
oh, I just found out that  #51 will do the exact same thing. I'll close my PR then. Sorry for the noise.

#51 has been open for almost 2 years now; is no-one merging these?

**Comment by Phlosioneer** [comment]
@tijn no one is maintaining this project anymore, sadly. :(

**Comment by tijn** [comment]
@Phlosioneer that's too bad. Should we do anything about it you think? Maybe someone can create a fork to merge all these pull requests... and then we could leave a new PR to point to the updated repo or so (?)

**Comment by Phlosioneer** [comment]
I've considered trying to maintain it. I don't have much free time, but this is a pretty low-maintenance book anyway. I don't know.

For now, I'm just watching it and reading all the PR's and issues.

**Comment by crclark96** [comment]
@Phlosioneer I definitely support forking. The original authors' emails are erik.helin@gmail.com and tgwizard@gmail.com if you wanted to let them know what you're planning on doing. 

You could also ask them to make a note of the fork in the README if they're not interested in merging anything back in anymore.

**Pull request closed without merging**
